// Detect a physical mobile device even when Chrome 'Desktop site' reports a wide CSS viewport.
(function(){
  const sw=window.screen&&window.screen.width||0;
  const coarse=window.matchMedia&&window.matchMedia('(pointer: coarse)').matches;
  if(sw && (sw<=600 || (coarse && sw<=900))) document.documentElement.classList.add('mobile-device');
})();
const base=(window.TASKYA_API_BASE||'http://127.0.0.1:8000/api').replace(/\/$/,''),chat=document.getElementById('chat'),form=document.getElementById('f'),input=document.getElementById('i'),lang=document.getElementById('lang'),mic=document.getElementById('mic'),events=document.getElementById('events'),cancel=document.getElementById('cancel'),file=document.getElementById('file'),fileBtn=document.getElementById('fileBtn'),webBtn=document.getElementById('webBtn'),voiceStatus=document.getElementById('voiceStatus'),historyEl=document.getElementById('history');
let current=null,lastAnswer='',webEnabled=false,isLoading=false;
const SESSION_KEY='taskya_session_id',HISTORY_KEY='taskya_chat_history_v2';
const sessionId=localStorage.getItem(SESSION_KEY)||crypto.randomUUID();localStorage.setItem(SESSION_KEY,sessionId);
function add(t,c){const e=document.createElement('div');e.className='m '+c;e.textContent=t;chat.appendChild(e);chat.scrollTop=chat.scrollHeight;return e}
function cleanChat(){chat.innerHTML='';}
function saveHistory(item){let all=[];try{all=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch(_){};const i=all.findIndex(x=>x.id===item.id);if(i>=0)all[i]={...all[i],...item};else all.unshift(item);all=all.slice(0,50);localStorage.setItem(HISTORY_KEY,JSON.stringify(all));renderHistory()}
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch(_){return[]}}
function renderHistory(){historyEl.innerHTML='';const all=getHistory();if(!all.length){historyEl.innerHTML='<div class="history-empty">Your recent tasks will appear here.</div>';return}all.forEach(x=>{const b=document.createElement('button');b.className='history-item'+(x.id===current?' active':'');b.textContent=x.question;b.title=x.question;b.onclick=()=>loadConversation(x);historyEl.appendChild(b)})}
function loadConversation(x){cleanChat();document.getElementById('welcome')?.remove();add(x.question,'u');if(x.answer)add(x.answer,'a');lastAnswer=x.answer||'';current=x.id;events.textContent=x.status==='completed'?'Completed':'Saved task';renderHistory();document.getElementById('sidebar').classList.remove('open')}
async function loadRemoteHistory(){try{const d=await postJSON(base+'/history?session_id='+encodeURIComponent(sessionId));(d.items||[]).forEach(x=>{if(!x.user_message)return;saveHistory({id:x.id,question:x.user_message,answer:x.result||'',status:x.status,createdAt:x.created_at})});}catch(_){}renderHistory()}
async function watch(id,question){const es=new EventSource(`${base}/task/${id}/events`);es.onmessage=e=>{const d=JSON.parse(e.data);events.textContent=d.event+(d.data?.tool?' • '+d.data.tool:'');if(d.event==='completed'){lastAnswer=d.data.answer||'';add(lastAnswer,'a');saveHistory({id,question,answer:lastAnswer,status:'completed',createdAt:new Date().toISOString()});cancel.disabled=true;isLoading=false}if(d.event==='approval_required'){add('⚠️ Human approval required. Review before approving.','a');saveHistory({id,question,answer:'Approval required',status:'approval_required',createdAt:new Date().toISOString()})}if(d.event==='error'){isLoading=false;cancel.disabled=true;add('Task failed. Please try again.','a')}if(d.event==='done'){es.close();isLoading=false;cancel.disabled=true}};es.onerror=()=>{es.close();if(isLoading){events.textContent='Connection interrupted';isLoading=false;cancel.disabled=true}}}
async function postJSON(url,options={}){const r=await fetch(url,options);let d={};try{d=await r.json()}catch(_){d={detail:await r.text()}}if(!r.ok)throw new Error(d.detail||d.message||'Backend request failed');return d}
form.onsubmit=async e=>{e.preventDefault();const t=input.value.trim();if(!t||isLoading)return;document.getElementById('welcome')?.remove();add(t,'u');input.value='';isLoading=true;events.textContent=webEnabled?'Web search enabled • Connecting…':'Connecting to Taskya AI…';try{const d=await postJSON(base+'/task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,language:lang.value,web_enabled:webEnabled,session_id:sessionId})});current=d.task_id;saveHistory({id:current,question:t,answer:'',status:'queued',createdAt:new Date().toISOString()});cancel.disabled=false;renderHistory();watch(current,t)}catch(err){isLoading=false;events.textContent='Backend connection failed';add('Backend not connected: '+err.message,'a')}};
cancel.onclick=async()=>{if(current)await fetch(`${base}/task/${current}/cancel`,{method:'POST'});cancel.disabled=true;isLoading=false;events.textContent='Cancellation requested'};
webBtn.onclick=()=>{webEnabled=!webEnabled;webBtn.classList.toggle('active',webEnabled);webBtn.title=webEnabled?'Web search ON':'Use web search';events.textContent=webEnabled?'Web search enabled':'Web search auto'};
fileBtn.onclick=()=>file.click();
file.onchange=async()=>{if(!file.files[0])return;const fd=new FormData();fd.append('file',file.files[0]);voiceStatus.textContent='Uploading…';try{const d=await postJSON(base+'/upload',{method:'POST',body:fd});input.value+=`${input.value?'\n\n':''}Uploaded file: ${d.filename}. Analyze it.`;voiceStatus.textContent='File attached';setTimeout(()=>voiceStatus.textContent='',1800)}catch(err){add('Upload failed: '+err.message,'a');voiceStatus.textContent='Upload failed'}file.value=''};
function speechLang(){const v=lang.value;return v==='en'?'en-IN':v==='mr'?'mr-IN':v==='bn'?'bn-IN':v==='ta'?'ta-IN':v==='te'?'te-IN':'hi-IN'}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=null,voiceStarting=false;if(!SR){mic.title='Voice input needs a supported browser such as Chrome on Android';voiceStatus.textContent='Voice unavailable';}else{rec=new SR();rec.interimResults=true;rec.continuous=false;rec.maxAlternatives=1;rec.onstart=()=>{voiceStarting=false;voiceStatus.textContent='Listening…';mic.classList.add('listening');mic.setAttribute('aria-pressed','true')};rec.onend=()=>{voiceStarting=false;mic.classList.remove('listening');mic.setAttribute('aria-pressed','false');if(voiceStatus.textContent==='Listening…')voiceStatus.textContent='';};rec.onerror=e=>{voiceStarting=false;mic.classList.remove('listening');mic.setAttribute('aria-pressed','false');const map={"not-allowed":'Microphone permission blocked. Allow microphone access.',"service-not-allowed":'Voice service is blocked in this browser.',"audio-capture":'No microphone was found.',"network":'Voice service network error.'};voiceStatus.textContent=map[e.error]||'Voice input unavailable';};rec.onnomatch=()=>{voiceStatus.textContent='Could not understand. Try again.'};rec.onresult=e=>{const text=Array.from(e.results).map(r=>r[0].transcript).join(' ').trim();if(text){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();voiceStatus.textContent='Voice captured ✓'}};mic.onclick=async()=>{if(voiceStarting)return;voiceStarting=true;voiceStatus.textContent='Starting microphone…';try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}rec.lang=speechLang();rec.start()}catch(e){voiceStarting=false;mic.classList.remove('listening');mic.setAttribute('aria-pressed','false');if(e.name==='NotAllowedError'||e.name==='PermissionDeniedError')voiceStatus.textContent='Microphone permission blocked. Allow it in browser settings.';else if(e.name==='NotFoundError')voiceStatus.textContent='No microphone found.';else voiceStatus.textContent='Could not start voice. Tap again.';}}}
document.getElementById('speak').onclick=()=>{if(!lastAnswer||!('speechSynthesis' in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(lastAnswer);u.lang=speechLang();const voices=speechSynthesis.getVoices();const match=voices.find(v=>v.lang.toLowerCase().startsWith(u.lang.slice(0,2).toLowerCase()));if(match)u.voice=match;speechSynthesis.speak(u)};
document.getElementById('newChat').onclick=()=>{current=null;lastAnswer='';cleanChat();chat.innerHTML='<div id="welcome"><div class="welcome-icon">✦</div><h2>Ask Taskya anything...</h2><p>Research, websites, files, Excel/PDF, calculations and multi-step tasks.</p></div>';events.textContent='Ready';input.focus();renderHistory();document.getElementById('sidebar').classList.remove('open')};
const overlay=document.getElementById('overlay'),contactModal=document.getElementById('contactModal'),paymentModal=document.getElementById('paymentModal');const contactEmail=window.TASKYA_CONTACT_EMAIL||'info@taskar.in';document.getElementById('contactEmail').textContent=contactEmail;document.getElementById('contactMail').textContent=contactEmail;document.getElementById('contactMail').href='mailto:'+contactEmail;
function openModal(m){overlay.classList.add('open');m.classList.add('open');m.setAttribute('aria-hidden','false')}function closeModals(){overlay.classList.remove('open');[contactModal,paymentModal].forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')})}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModals);overlay.onclick=closeModals;document.getElementById('contactBtn').onclick=()=>openModal(contactModal);document.getElementById('contactFooter').onclick=()=>openModal(contactModal);document.getElementById('upgradeBtn').onclick=()=>openModal(paymentModal);document.getElementById('upgradeTop').onclick=()=>openModal(paymentModal);document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('payBtn').onclick=async()=>{const btn=document.getElementById('payBtn'),status=document.getElementById('paymentStatus');btn.disabled=true;status.textContent='Creating secure order…';try{const order=await postJSON(base+'/billing/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId})});if(!window.Razorpay)throw new Error('Razorpay checkout could not load');const rzp=new Razorpay({key:order.key_id,amount:order.amount,currency:order.currency,name:order.name,description:order.description,order_id:order.order_id,prefill:order.prefill,theme:{color:'#1769e8'},handler:async response=>{try{await postJSON(base+'/billing/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...response,session_id:sessionId})});status.textContent='Payment verified successfully.';btn.textContent='Payment complete ✓'}catch(err){status.textContent='Payment received but verification failed: '+err.message}}});rzp.on('payment.failed',r=>{status.textContent='Payment failed: '+(r.error?.description||'Please try again.');btn.disabled=false});rzp.open()}catch(err){status.textContent=err.message;btn.disabled=false}};
renderHistory();loadRemoteHistory();
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
