window.TASKYA_CONFIG={
  API_BASE_URL:'https://taskya-ai-core.onrender.com',
  SUPABASE_URL:'',
  SUPABASE_ANON_KEY:'',
  RAZORPAY_KEY_ID:'',
  SUPPORT_EMAIL:'info@taskya.in',
  FREE_TASK_LIMIT:10,
  PRO_PRICE_INR:19
};
